### ISSUE TITLE
Couldn't find preset "next/babel" with Yarn package manager

### ISSUE THREAD

**Issue by tgoldenberg** [mars/heroku-nextjs#7]
<img width="977" alt="screen shot 2017-02-03 at 12 19 29 pm" src="https://cloud.githubusercontent.com/assets/10930134/22601035/2d3d6638-ea0b-11e6-87c7-326fd7ff2645.png">

With `package.json`

```
{
  "name": "commandiv-next",
  "version": "1.0.0",
  "description": "Commandiv Marketing website",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "next build",
    "start": "next start -p $PORT",
    "dev": "next",
    "postinstall": "heroku-nextjs-build"
  },
  "author": "tgoldenberg",
  "dependencies": {
    "@mars/heroku-nextjs-build": "^1.1.0",
    "babel-plugin-wrap-in-js": "^1.1.1",
    "fs": "^0.0.1-security",
    "lodash": "^4.17.4",
    "material-ui": "^0.16.7",
    "next": "^2.0.0-beta.22",
    "node-sass": "^4.5.0",
    "raw-loader": "^0.5.1",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-pure-render-mixin": "^15.4.2",
    "react-addons-transition-group": "^15.4.2",
    "react-ga": "^2.1.2",
    "react-redux": "^5.0.2",
    "react-social-icons": "^2.5.1",
    "react-tap-event-plugin": "^2.0.1",
    "redux": "^3.6.0",
    "redux-thunk": "^2.2.0",
    "sass-loader": "^4.1.1",
    "webpack": "^1.14.0"
  },
  "engines": {
    "node": "6.9.x"
  },
  "cacheDirectories": [
    "nextjs/node_modules"
  ]
}

```

**Comment by tgoldenberg** [comment]
`.babelrc`
```
{
  "plugins": [
    [
      "wrap-in-js",
      {
        "extensions": ["css$", "scss$"]
      }
    ]
  ],
  "presets": [
    "next/babel"
  ],
  "ignore": []
}


```

**Comment by mars** [comment]
What is the error? Please post the build output.

**Comment by tgoldenberg** [comment]
Here's the full output:
```
Counting objects: 15, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (14/14), done.
Writing objects: 100% (15/15), 1.77 KiB | 0 bytes/s, done.
Total 15 (delta 7), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Node.js app detected
remote:
remote: -----> Creating runtime environment
remote:
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:
remote: -----> Installing binaries
remote:        engines.node (package.json):  6.9.x
remote:        engines.npm (package.json):   unspecified (use default)
remote:
remote:        Resolving node version 6.9.x via semver.io...
remote:        Downloading and installing node 6.9.5...
remote:        Using default npm version: 3.10.10
remote:        Resolving yarn version (latest) via semver.io...
remote:        Downloading and installing yarn (0.19.1)...
remote:        Installed yarn 0.19.1
remote:
remote: -----> Restoring cache
remote:        Loading 1 from cacheDirectories (package.json):
remote:        - nextjs/node_modules (not cached - skipping)
remote:
remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v0.19.1
remote:        warning commandiv-next@1.0.0: No license field
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        warning fsevents@1.0.17: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning "material-ui@0.16.7" has unmet peer dependency "react@^15.0.0".
remote:        warning "material-ui@0.16.7" has unmet peer dependency "react-dom@^15.0.0".
remote:        warning "react-addons-css-transition-group@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-addons-pure-render-mixin@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-addons-transition-group@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-ga@2.1.2" has unmet peer dependency "react@>= 0.14.0".
remote:        warning "react-redux@5.0.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0".
remote:        warning "react-social-icons@2.5.1" has unmet peer dependency "react@0.13.x || 0.14.x || 15.x.x".
remote:        warning "react-tap-event-plugin@2.0.1" has unmet peer dependency "react@^15.4.0-0".
remote:        warning "react-tap-event-plugin@2.0.1" has unmet peer dependency "react-dom@^15.4.0-0".
remote:        warning "react-addons-create-fragment@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        warning "react-event-listener@0.4.1" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
remote:        warning "recompose@0.21.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0".
remote:        warning "glob-promise@2.0.0" has unmet peer dependency "glob@*".
remote:        warning "react-addons-shallow-compare@15.4.2" has unmet peer dependency "react@^15.4.2".
remote:        [4/4] Building fresh packages...
remote:        $ heroku-nextjs-build
remote:
remote:        > commandiv-next@1.0.0 build /app/nextjs
remote:        > next build
remote:
remote:        { Error: ./pages/index.js
remote:        Module build failed: Error: Couldn't find preset "next/babel" relative to directory "/app/nextjs"
remote:        at /app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
remote:        at Array.map (native)
remote:        at OptionManager.resolvePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
remote:        at OptionManager.mergePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
remote:        at OptionManager.mergeOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
remote:        at OptionManager.init (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
remote:        at File.initOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:216:65)
remote:        at new File (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:139:24)
remote:        at Pipeline.transform (/app/nextjs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
remote:        at transpile (/app/nextjs/node_modules/babel-loader/lib/index.js:41:20)
remote:        @ multi bundles/pages/index.js
remote:        at /app/nextjs/node_modules/next/dist/server/build/index.js:650:55
remote:        at Compiler.<anonymous> (/app/nextjs/node_modules/next/node_modules/webpack/lib/Compiler.js:194:14)
remote:        at Compiler.emitRecords (/app/nextjs/node_modules/next/node_modules/webpack/lib/Compiler.js:282:37)
remote:        at Compiler.<anonymous> (/app/nextjs/node_modules/next/node_modules/webpack/lib/Compiler.js:187:11)
remote:        at /app/nextjs/node_modules/next/node_modules/webpack/lib/Compiler.js:275:11
remote:        at Compiler.applyPluginsAsync (/app/nextjs/node_modules/tapable/lib/Tapable.js:60:69)
remote:        at Compiler.afterEmit (/app/nextjs/node_modules/next/node_modules/webpack/lib/Compiler.js:272:8)
remote:        at Compiler.<anonymous> (/app/nextjs/node_modules/next/node_modules/webpack/lib/Compiler.js:267:14)
remote:        at /app/nextjs/node_modules/async/lib/async.js:52:16
remote:        at done (/app/nextjs/node_modules/async/lib/async.js:246:17)
remote:        errors:
remote:        [ './pages/index.jsnModule build failed: Error: Couldn't find preset "next/babel" relative to directory "/app/nextjs"n    at /app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19n    at Array.map (native)n    at OptionManager.resolvePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)n    at OptionManager.mergePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)n    at OptionManager.mergeOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)n    at OptionManager.init (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)n    at File.initOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:216:65)n    at new File (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:139:24)n    at Pipeline.transform (/app/nextjs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)n    at transpile (/app/nextjs/node_modules/babel-loader/lib/index.js:41:20)n @ multi bundles/pages/index.js',
remote:        './pages/waitlist.jsnModule build failed: Error: Couldn't find preset "next/babel" relative to directory "/app/nextjs"n    at /app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19n    at Array.map (native)n    at OptionManager.resolvePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)n    at OptionManager.mergePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)n    at OptionManager.mergeOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)n    at OptionManager.init (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)n    at File.initOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:216:65)n    at new File (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:139:24)n    at Pipeline.transform (/app/nextjs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)n    at transpile (/app/nextjs/node_modules/babel-loader/lib/index.js:41:20)n @ multi bundles/pages/waitlist.js',
remote:        './~/next/dist/pages/_error.jsnModule build failed: Error: Couldn't find preset "next/babel" relative to directory "/app/nextjs"n    at /app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19n    at Array.map (native)n    at OptionManager.resolvePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)n    at OptionManager.mergePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)n    at OptionManager.mergeOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)n    at OptionManager.init (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)n    at File.initOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:216:65)n    at new File (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:139:24)n    at Pipeline.transform (/app/nextjs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)n    at transpile (/app/nextjs/node_modules/babel-loader/lib/index.js:41:20)n @ multi bundles/pages/_error.js',
remote:        './~/next/dist/pages/_error-debug.jsnModule build failed: Error: Couldn't find preset "next/babel" relative to directory "/app/nextjs"n    at /app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19n    at Array.map (native)n    at OptionManager.resolvePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)n    at OptionManager.mergePresets (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)n    at OptionManager.mergeOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)n    at OptionManager.init (/app/nextjs/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)n    at File.initOptions (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:216:65)n    at new File (/app/nextjs/node_modules/babel-core/lib/transformation/file/index.js:139:24)n    at Pipeline.transform (/app/nextjs/node_modules/babel-core/lib/transformation/pipeline.js:46:16)n    at transpile (/app/nextjs/node_modules/babel-loader/lib/index.js:41:20)' ],
remote:        warnings: [] }
remote:
remote:        npm ERR! Linux 3.13.0-105-generic
remote:        npm ERR! argv "/tmp/build_2a9ab498b32ffdedecd823d1acbfe9f1/.heroku/node/bin/node" "/tmp/build_2a9ab498b32ffdedecd823d1acbfe9f1/.heroku/node/bin/npm" "run" "build"
remote:        npm ERR! node v6.9.5
remote:        npm ERR! npm  v3.10.10
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! commandiv-next@1.0.0 build: `next build`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the commandiv-next@1.0.0 build script 'next build'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the commandiv-next package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     next build
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs commandiv-next
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls commandiv-next
remote:        npm ERR! There is likely additional logging output above.
remote:
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /app/nextjs/npm-debug.log
remote:        error Command failed with exit code 1.
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote:
remote: -----> Build failed
remote:
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:
remote:        Some possible problems:
remote:
remote:        - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
remote:        https://devcenter.heroku.com/articles/nodejs-support#build-behavior
remote:
remote:        Love,
remote:        Heroku
remote:
remote:  !     Push rejected, failed to compile Node.js app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to safe-coast-21069.
remote:
To https://git.heroku.com/safe-coast-21069.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/safe-coast-21069.git'
```

**Comment by mars** [comment]
I see you're using yarn. Looks like this might fix it:
https://github.com/zeit/next.js/issues/810

**Comment by tgoldenberg** [comment]
Yep. Thanks!
